service: mouro

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-aws-alerts


provider:
   name: aws
   runtime: nodejs8.10
   region: us-west-2

custom: ${file(serverless-custom.yml)}
  
functions:
 graphql:
    handler: src/api_handler.graphql
    timeout: 30 #Max (ApiGateway limitation)
    events:
    - http:
        path: /graphql
        method: post
        cors: true