service: lambda-mouro

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-aws-alerts


provider:
   name: aws
   runtime: nodejs8.10
   stage: develop
   region: us-west-2

custom:
  domainName: 
    develop: api.uport.space
    master: api.uport.me
  customDomain:
    domainName: ${self:custom.domainName.${opt:stage, self:provider.stage}}
    basePath: mouro
    createRoute53Record: false
    baseUrl: https://${self:custom.customDomain.domainName}/${self:custom.customDomain.basePath}
  alerts:
    dashboards: true
    topics:
      alarm: arn:aws:sns:us-west-2:113196216558:cloudwatch-alarm-to-slack
    definitions: 
      functionDuration:
        threshold: 3000 # override avereage duration alert
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration

functions:
 graphql:
    handler: src/api_handler.graphql
    timeout: 30 #Max (ApiGateway limitation)
    events:
    - http:
        path: /graphql
        method: post
        cors: true