service: mouro

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-aws-alerts

provider:
   name: aws
   runtime: nodejs8.10
   region: us-west-2
   environment:
      DYNAMODB_TABLE: ${self:service}-${opt:stage}
   iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

custom: ${file(serverless-config/serverless-custom.yml)}
  
functions:
  - ${file(serverless-config/functions.yml)}

resources:
  - ${file(serverless-config/dynamodb.yml)}