Resources:
  
  ConnectionsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # see DynamoDBConnectionManager
      TableName: Connections
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        # connection id
        - AttributeName: id
          KeyType: HASH

  SubscriptionsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # see DynamoDBSubscriptionManager
      TableName: Subscriptions
      AttributeDefinitions:
        - AttributeName: event
          AttributeType: S
        - AttributeName: subscriptionId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: event
          KeyType: HASH
        - AttributeName: subscriptionId
          KeyType: RANGE

  SubscriptionOperationsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # see DynamoDBSubscriptionManager
      TableName: SubscriptionOperations
      AttributeDefinitions:
        - AttributeName: subscriptionId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: subscriptionId
          KeyType: HASH
